# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Nextiva,Inc.NextivaApp
PackageVersion: 22.9.31.119
PackageLocale: en-US
Publisher: Nextiva, Inc
PackageName: Nextiva App
License: NextOS
ShortDescription: Nextiva Desktop App
ManifestType: defaultLocale
ManifestVersion: 1.1.0

